//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAPD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComboSetItem
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public int ComboSetId { get; set; }
    
        public virtual ComboSet ComboSet { get; set; }
        public virtual Productx Productx { get; set; }
    }
}
