//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerDIY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itemx
    {
        public int Id { get; set; }
        public Nullable<int> Bill_Id { get; set; }
        public int ProductID { get; set; }
        public int Price { get; set; }
    
        public virtual Billx Billx { get; set; }
        public virtual Productx Productx { get; set; }
    }
}
