//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputerDIY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productx
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productx()
        {
            this.Itemxes = new HashSet<Itemx>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int UnitPrice { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public int ProductId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Itemx> Itemxes { get; set; }
        public virtual TypeProductx TypeProductx { get; set; }
    }
}
